-- phpMyAdmin SQL Dump
-- version 4.7.0
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: Jul 25, 2018 at 06:45 PM
-- Server version: 5.7.22-0ubuntu0.16.04.1
-- PHP Version: 7.1.19-1+ubuntu16.04.1+deb.sury.org+1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `courseDB`
--

-- --------------------------------------------------------

--
-- Table structure for table `courseDataTable`
--

CREATE TABLE `courseDataTable` (
  `conceptCode` int(100) NOT NULL,
  `mathTopic` varchar(100) NOT NULL,
  `topic_label` varchar(200) DEFAULT NULL,
  `mathKitName` varchar(200) NOT NULL,
  `mathConcept` varchar(200) NOT NULL,
  `standardSelect` varchar(200) NOT NULL,
  `keyWordTag` varchar(200) NOT NULL,
  `preReqConcept` text NOT NULL,
  `procedureTeacher` text NOT NULL,
  `kitLimitation` text NOT NULL,
  `realLifeExample` text NOT NULL,
  `alternativeMethod` text NOT NULL,
  `mathKitDemoLink` varchar(500) NOT NULL,
  `hardspotConceptQuestionLink` varchar(500) NOT NULL,
  `quizConceptLink` varchar(500) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `courseDataTable`
--

INSERT INTO `courseDataTable` (`conceptCode`, `mathTopic`, `topic_label`, `mathKitName`, `mathConcept`, `standardSelect`, `keyWordTag`, `preReqConcept`, `procedureTeacher`, `kitLimitation`, `realLifeExample`, `alternativeMethod`, `mathKitDemoLink`, `hardspotConceptQuestionLink`, `quizConceptLink`) VALUES
(1010101, 'NumberSystem', 'Number System', 'Math Kit 1', '2 digit addition with and without carry', 'Grade 1', 'Addition, Grade 1', '1 digit addition without carry, 1 digit addition with carry', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'https://www.youtube.com/watch?v=uWBZF-Lyq58', 'https://learninglinksindia-my.sharepoint.com/:b:/g/personal/shivranjan_kolvankar_learninglinksindia_org/EYluJdpmh65AqNYUm-vIVccBsVKVLd-68dB8OJiHFGCZIw?e=baSeRr', 'https://learninglinksindia-my.sharepoint.com/:b:/g/personal/shivranjan_kolvankar_learninglinksindia_org/ES00UULuZN5Ns0TWLPssANsBibfC_u_Z-OKqIyvWAO9B9w?e=TE9jta'),
(1010102, 'NumberSystem', 'Number System', 'Math Kit 1', '3 digit addition with and without carry', 'Grade 1', 'Addition, Grade 1', '1 digit addition without carry, 1 digit addition with carry', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'https://www.youtube.com/watch?v=uWBZF-Lyq58', 'https://learninglinksindia-my.sharepoint.com/:b:/g/personal/shivranjan_kolvankar_learninglinksindia_org/EYluJdpmh65AqNYUm-vIVccBsVKVLd-68dB8OJiHFGCZIw?e=baSeRr', 'https://learninglinksindia-my.sharepoint.com/:b:/g/personal/shivranjan_kolvankar_learninglinksindia_org/ES00UULuZN5Ns0TWLPssANsBibfC_u_Z-OKqIyvWAO9B9w?e=TE9jta'),
(1010103, 'NumberSystem', 'Number System', 'Math Kit 2', '2 digit subtractionwith and without carry', 'Grade 1', 'Addition, Grade 1', '1 digit addition without carry, 1 digit addition with carry', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'https://www.youtube.com/watch?v=uWBZF-Lyq58', 'https://learninglinksindia-my.sharepoint.com/:b:/g/personal/shivranjan_kolvankar_learninglinksindia_org/EYluJdpmh65AqNYUm-vIVccBsVKVLd-68dB8OJiHFGCZIw?e=baSeRr', 'https://learninglinksindia-my.sharepoint.com/:b:/g/personal/shivranjan_kolvankar_learninglinksindia_org/ES00UULuZN5Ns0TWLPssANsBibfC_u_Z-OKqIyvWAO9B9w?e=TE9jta'),
(1010104, 'NumberSystem', 'Number System', 'Math Kit 2', '2 digit subtractionwith and without carry', 'Grade 4', 'Addition, Grade 1', '1 digit addition without carry, 1 digit addition with carry', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'https://www.youtube.com/watch?v=uWBZF-Lyq58', 'https://learninglinksindia-my.sharepoint.com/:b:/g/personal/shivranjan_kolvankar_learninglinksindia_org/EYluJdpmh65AqNYUm-vIVccBsVKVLd-68dB8OJiHFGCZIw?e=baSeRr', 'https://learninglinksindia-my.sharepoint.com/:b:/g/personal/shivranjan_kolvankar_learninglinksindia_org/ES00UULuZN5Ns0TWLPssANsBibfC_u_Z-OKqIyvWAO9B9w?e=TE9jta'),
(1010105, 'NumberSystem', 'Number System', 'Math Kit 2', '2 digit subtractionwith and without carry', 'Grade 3', 'Addition, Grade 1', '1 digit addition without carry, 1 digit addition with carry', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'https://www.youtube.com/watch?v=uWBZF-Lyq58', 'https://learninglinksindia-my.sharepoint.com/:b:/g/personal/shivranjan_kolvankar_learninglinksindia_org/EYluJdpmh65AqNYUm-vIVccBsVKVLd-68dB8OJiHFGCZIw?e=baSeRr', 'https://learninglinksindia-my.sharepoint.com/:b:/g/personal/shivranjan_kolvankar_learninglinksindia_org/ES00UULuZN5Ns0TWLPssANsBibfC_u_Z-OKqIyvWAO9B9w?e=TE9jta'),
(1010106, 'NumberSystem', 'Number System', 'Math Kit 3', '2 digit subtractionwith and without carry', 'Grade 1', 'Addition, Grade 1', '1 digit addition without carry, 1 digit addition with carry', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'https://www.youtube.com/watch?v=uWBZF-Lyq58', 'https://learninglinksindia-my.sharepoint.com/:b:/g/personal/shivranjan_kolvankar_learninglinksindia_org/EYluJdpmh65AqNYUm-vIVccBsVKVLd-68dB8OJiHFGCZIw?e=baSeRr', 'https://learninglinksindia-my.sharepoint.com/:b:/g/personal/shivranjan_kolvankar_learninglinksindia_org/ES00UULuZN5Ns0TWLPssANsBibfC_u_Z-OKqIyvWAO9B9w?e=TE9jta');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `courseDataTable`
--
ALTER TABLE `courseDataTable`
  ADD PRIMARY KEY (`conceptCode`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
